### PR TITLE
Allow users to download wallpapers 

### PR DESCRIPTION
**Pull request by AsianCat54x**
I have created buttons over each image with a download logo. Whenever the user will click it, the specific image will get downloaded!

PS: Currently, whenever the button is clicked, the image is downloaded, as well as the preview is opened on a new browser page (This is the default one). The user is first redirected and then the downloading starts. If you want, I can remove the new page popup.

### CODE REVIEW

**Comment by linuxdotexe** [comment]
this is amazing! thanks for contributing!

i'm new to webdev... does the single quotes and double quotes usage make a difference?

**Comment by AsianCat54x** [comment]
That's a tricky question, haha. Like in some of the languages (eg. Java) we use single quotes for characters whereas double quotes for strings. But in some languages, using both the literals does the same thing (eg. Python, JavaScript), I guess. It's just based on the standard code style we use for specific programming language.

**Comment by linuxdotexe** [comment]
Oh! that's good to know! I only used python like in the past two years so it didn't matter between them for me😅

**Comment by AsianCat54x** [comment]
Oh I see! BTW, I guess those changing of the quotes was done by the linter :')

**Pull request merged**
